# Generated by Django 2.2.7 on 2019-11-24 04:20

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='user_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(srid=4326, x=42.408532, y=-71.118059), srid=4326),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(srid=4326, x=42.408532, y=-71.118059), srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(srid=4326, x=42.408532, y=-71.118059), srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(srid=4326, x=42.408532, y=-71.118059), srid=4326),
        ),
    ]
