# Generated by Django 2.2.7 on 2019-11-24 04:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191124_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user_loc',
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
